name: Android Integration Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [32]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          arch: 'x86_64'
          target: google_apis
          api-level: ${{ matrix.api-level }}
          profile: Nexus 6
          script: ./gradlew connectedAndroidTest --stacktrace
